<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net9.0;net10.0</TargetFrameworks>
    <RootNamespace>Jellyfin.Plugin.HyperionGrabber.Core.Tests</RootNamespace>
    <OutputType>Exe</OutputType>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <AnalysisMode>Recommended</AnalysisMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="Google.FlatBuffers" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Jellyfin.Plugin.HyperionGrabber.Core\Jellyfin.Plugin.HyperionGrabber.Core.csproj" />
    <ProjectReference Include="..\Jellyfin.Plugin.HyperionGrabber.TestSupport\Jellyfin.Plugin.HyperionGrabber.TestSupport.csproj" />
  </ItemGroup>

</Project>
